version: '3'


services:
  app:
    container_name: tvmultiverse28
    restart: always
    image: biganshagarwal/tvmultiverse28
    build: .
    volumes: 
      - .:/app
    ports:
      - '8080:3000'
    env_file: .env
    links:
      - mongo
    networks:
      - app-network

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - app-network

      
networks:
  app-network:
    driver: bridge
